apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-qa
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kodavara/devsecops-demo.git
    targetRevision: HEAD
    path: ecommerce
    helm:
      valueFiles:
        - values-qa.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: ecommerce-qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
